In [176]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [177]:
df = pd.read_csv("WA_Fn-UseC_-Telco-Customer-Churn.csv")

In [178]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [179]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [180]:
df.describe()

       SeniorCitizen       tenure  MonthlyCharges
count    7043.000000  7043.000000     7043.000000
mean        0.162147    32.371149       64.761692
std         0.368612    24.559481       30.090047
min         0.000000     0.000000       18.250000
25%         0.000000     9.000000       35.500000
50%         0.000000    29.000000       70.350000
75%         0.000000    55.000000       89.850000
max         1.000000    72.000000      118.750000

In [181]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [182]:
df_m=df

In [183]:
df_m['gender']=df_m['gender'].map({'Female':1,'Male':0})

In [184]:
df_m['is_female']=df_m['gender']

In [185]:
df_m=df_m.rename(columns={'gender':'is_female'})

In [186]:
df_m['Partner'].count()

np.int64(7043)

In [187]:
df_m.columns[df_m.columns.duplicated()]

Index(['is_female'], dtype='object')

In [188]:
df_m

,customerID,is_female,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,is_female
0,7590-VHVEG,1,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No,1
1,5575-GNVDE,0,0,No,No,34,Yes,No,DSL,Yes,...,No,No,No,One year,No,Mailed check,56.95,1889.5,No,0
2,3668-QPYBK,0,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,0
3,7795-CFOCW,0,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No,0
4,9237-HQITU,1,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,0,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No,0
7039,2234-XADUH,1,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No,1
7040,4801-JZAZL,1,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No,1
7041,8361-LTMKD,0,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes,0
7042,3186-AJIEK,0,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No,0

In [189]:
print(df_m.columns[df_m.columns.duplicated()])

Index(['is_female'], dtype='object')

In [190]:
df_m

,customerID,is_female,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,is_female
0,7590-VHVEG,1,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No,1
1,5575-GNVDE,0,0,No,No,34,Yes,No,DSL,Yes,...,No,No,No,One year,No,Mailed check,56.95,1889.5,No,0
2,3668-QPYBK,0,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,0
3,7795-CFOCW,0,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No,0
4,9237-HQITU,1,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,0,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No,0
7039,2234-XADUH,1,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No,1
7040,4801-JZAZL,1,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No,1
7041,8361-LTMKD,0,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes,0
7042,3186-AJIEK,0,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No,0

In [191]:
df_m = df_m.loc[:, ~df_m.columns.duplicated()]

In [192]:
df_m

,customerID,is_female,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,1,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,0,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,0,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,0,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,1,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,0,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,1,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,1,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,0,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,0,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [193]:
df['Partner'].value_counts()

Partner
No     3641
Yes    3402
Name: count, dtype: int64

In [194]:
df_m['Partner']=df_m['Partner'].map({'No':1,'Yes':1})

C:\Users\Standby\AppData\Local\Temp\ipykernel_11632\811189281.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_m['Partner']=df_m['Partner'].map({'No':1,'Yes':1})

In [195]:
df_m=df_m.rename(columns={'Partner':'Partner_No'})

In [196]:
df_m.head()

,customerID,is_female,SeniorCitizen,Partner_No,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,1,0,1,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,0,0,1,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,0,0,1,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,0,0,1,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,1,0,1,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [197]:
binary_cols = ['Dependents', 'PhoneService', 'TechSupport', 
               'StreamingTV', 'StreamingMovies', 'PaperlessBilling', 'Churn',]

for col in binary_cols:
    unique_vals = set(df[col].unique())
    if unique_vals <= {'Yes', 'No'}:
        print(f"{col}: OK - only Yes/No -> {unique_vals}")
    else:
        print(f"{col}: WARNING - extra values found -> {unique_vals}")

Dependents: OK - only Yes/No -> {'No', 'Yes'}
PhoneService: OK - only Yes/No -> {'No', 'Yes'}
TechSupport: WARNING - extra values found -> {'No', 'Yes', 'No internet service'}
StreamingTV: WARNING - extra values found -> {'No', 'Yes', 'No internet service'}
StreamingMovies: WARNING - extra values found -> {'No', 'Yes', 'No internet service'}
PaperlessBilling: OK - only Yes/No -> {'Yes', 'No'}
Churn: OK - only Yes/No -> {'No', 'Yes'}

In [198]:
binary_cols = ['Dependents', 'PhoneService', 
                'PaperlessBilling', 'Churn']

for col in binary_cols:
    df_m[col] = df_m[col].map({'Yes': 1, 'No': 0})

df_m[binary_cols].head()

   Dependents  PhoneService  PaperlessBilling  Churn
0           0             0                 1      0
1           0             1                 0      0
2           0             1                 1      1
3           0             0                 0      0
4           0             1                 1      1

In [199]:
df_m

,customerID,is_female,SeniorCitizen,Partner_No,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,1,0,1,0,1,0,No phone service,DSL,No,...,No,No,No,No,Month-to-month,1,Electronic check,29.85,29.85,0
1,5575-GNVDE,0,0,1,0,34,1,No,DSL,Yes,...,Yes,No,No,No,One year,0,Mailed check,56.95,1889.5,0
2,3668-QPYBK,0,0,1,0,2,1,No,DSL,Yes,...,No,No,No,No,Month-to-month,1,Mailed check,53.85,108.15,1
3,7795-CFOCW,0,0,1,0,45,0,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,0,Bank transfer (automatic),42.30,1840.75,0
4,9237-HQITU,1,0,1,0,2,1,No,Fiber optic,No,...,No,No,No,No,Month-to-month,1,Electronic check,70.70,151.65,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,0,0,1,1,24,1,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,1,Mailed check,84.80,1990.5,0
7039,2234-XADUH,1,0,1,1,72,1,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,1,Credit card (automatic),103.20,7362.9,0
7040,4801-JZAZL,1,0,1,1,11,0,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,1,Electronic check,29.60,346.45,0
7041,8361-LTMKD,0,1,1,0,4,1,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,1,Mailed check,74.40,306.6,1
7042,3186-AJIEK,0,0,1,0,66,1,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,1,Bank transfer (automatic),105.65,6844.5,0

In [200]:
df_m['TechSupport'].value_counts()

TechSupport
No                     3473
Yes                    2044
No internet service    1526
Name: count, dtype: int64

In [201]:
df_m = pd.get_dummies(df_m, columns=['TechSupport'], prefix='TechSupport')

In [202]:
df_m

,customerID,is_female,SeniorCitizen,Partner_No,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,TechSupport_No,TechSupport_No internet service,TechSupport_Yes
0,7590-VHVEG,1,0,1,0,1,0,No phone service,DSL,No,...,No,Month-to-month,1,Electronic check,29.85,29.85,0,True,False,False
1,5575-GNVDE,0,0,1,0,34,1,No,DSL,Yes,...,No,One year,0,Mailed check,56.95,1889.5,0,True,False,False
2,3668-QPYBK,0,0,1,0,2,1,No,DSL,Yes,...,No,Month-to-month,1,Mailed check,53.85,108.15,1,True,False,False
3,7795-CFOCW,0,0,1,0,45,0,No phone service,DSL,Yes,...,No,One year,0,Bank transfer (automatic),42.30,1840.75,0,False,False,True
4,9237-HQITU,1,0,1,0,2,1,No,Fiber optic,No,...,No,Month-to-month,1,Electronic check,70.70,151.65,1,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,0,0,1,1,24,1,Yes,DSL,Yes,...,Yes,One year,1,Mailed check,84.80,1990.5,0,False,False,True
7039,2234-XADUH,1,0,1,1,72,1,Yes,Fiber optic,No,...,Yes,One year,1,Credit card (automatic),103.20,7362.9,0,True,False,False
7040,4801-JZAZL,1,0,1,1,11,0,No phone service,DSL,Yes,...,No,Month-to-month,1,Electronic check,29.60,346.45,0,True,False,False
7041,8361-LTMKD,0,1,1,0,4,1,Yes,Fiber optic,No,...,No,Month-to-month,1,Mailed check,74.40,306.6,1,True,False,False
7042,3186-AJIEK,0,0,1,0,66,1,No,Fiber optic,Yes,...,Yes,Two year,1,Bank transfer (automatic),105.65,6844.5,0,False,False,True

In [203]:
bool_cols = ['TechSupport_Yes', 'TechSupport_No internet service']  # adjust to your columns
df_m[bool_cols] = df_m[bool_cols].astype(int)

In [204]:
df_m

,customerID,is_female,SeniorCitizen,Partner_No,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,TechSupport_No,TechSupport_No internet service,TechSupport_Yes
0,7590-VHVEG,1,0,1,0,1,0,No phone service,DSL,No,...,No,Month-to-month,1,Electronic check,29.85,29.85,0,True,0,0
1,5575-GNVDE,0,0,1,0,34,1,No,DSL,Yes,...,No,One year,0,Mailed check,56.95,1889.5,0,True,0,0
2,3668-QPYBK,0,0,1,0,2,1,No,DSL,Yes,...,No,Month-to-month,1,Mailed check,53.85,108.15,1,True,0,0
3,7795-CFOCW,0,0,1,0,45,0,No phone service,DSL,Yes,...,No,One year,0,Bank transfer (automatic),42.30,1840.75,0,False,0,1
4,9237-HQITU,1,0,1,0,2,1,No,Fiber optic,No,...,No,Month-to-month,1,Electronic check,70.70,151.65,1,True,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,0,0,1,1,24,1,Yes,DSL,Yes,...,Yes,One year,1,Mailed check,84.80,1990.5,0,False,0,1
7039,2234-XADUH,1,0,1,1,72,1,Yes,Fiber optic,No,...,Yes,One year,1,Credit card (automatic),103.20,7362.9,0,True,0,0
7040,4801-JZAZL,1,0,1,1,11,0,No phone service,DSL,Yes,...,No,Month-to-month,1,Electronic check,29.60,346.45,0,True,0,0
7041,8361-LTMKD,0,1,1,0,4,1,Yes,Fiber optic,No,...,No,Month-to-month,1,Mailed check,74.40,306.6,1,True,0,0
7042,3186-AJIEK,0,0,1,0,66,1,No,Fiber optic,Yes,...,Yes,Two year,1,Bank transfer (automatic),105.65,6844.5,0,False,0,1

In [205]:
df_m.drop('TechSupport_No', axis=1, inplace=True)

In [206]:
df_m

,customerID,is_female,SeniorCitizen,Partner_No,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,TechSupport_No internet service,TechSupport_Yes
0,7590-VHVEG,1,0,1,0,1,0,No phone service,DSL,No,...,No,No,Month-to-month,1,Electronic check,29.85,29.85,0,0,0
1,5575-GNVDE,0,0,1,0,34,1,No,DSL,Yes,...,No,No,One year,0,Mailed check,56.95,1889.5,0,0,0
2,3668-QPYBK,0,0,1,0,2,1,No,DSL,Yes,...,No,No,Month-to-month,1,Mailed check,53.85,108.15,1,0,0
3,7795-CFOCW,0,0,1,0,45,0,No phone service,DSL,Yes,...,No,No,One year,0,Bank transfer (automatic),42.30,1840.75,0,0,1
4,9237-HQITU,1,0,1,0,2,1,No,Fiber optic,No,...,No,No,Month-to-month,1,Electronic check,70.70,151.65,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,0,0,1,1,24,1,Yes,DSL,Yes,...,Yes,Yes,One year,1,Mailed check,84.80,1990.5,0,0,1
7039,2234-XADUH,1,0,1,1,72,1,Yes,Fiber optic,No,...,Yes,Yes,One year,1,Credit card (automatic),103.20,7362.9,0,0,0
7040,4801-JZAZL,1,0,1,1,11,0,No phone service,DSL,Yes,...,No,No,Month-to-month,1,Electronic check,29.60,346.45,0,0,0
7041,8361-LTMKD,0,1,1,0,4,1,Yes,Fiber optic,No,...,No,No,Month-to-month,1,Mailed check,74.40,306.6,1,0,0
7042,3186-AJIEK,0,0,1,0,66,1,No,Fiber optic,Yes,...,Yes,Yes,Two year,1,Bank transfer (automatic),105.65,6844.5,0,0,1

In [207]:
df_m.value_counts()

customerID  is_female  SeniorCitizen  Partner_No  Dependents  tenure  PhoneService  MultipleLines     InternetService  OnlineSecurity       OnlineBackup         DeviceProtection     StreamingTV          StreamingMovies      Contract        PaperlessBilling  PaymentMethod              MonthlyCharges  TotalCharges  Churn  TechSupport_No internet service  TechSupport_Yes
0002-ORFBO  1          0              1           1           9       1             No                DSL              No                   Yes                  No                   Yes                  No                   One year        1                 Mailed check               65.60           593.3         0      0                                1                  1
6616-AALSR  1          0              1           1           65      1             Yes               Fiber optic      Yes                  No                   Yes                  Yes                  Yes                  Two year        1                 Credit card (automatic)    104.30          6725.3        0      0                                0                  1
6625-UTXEW  1          0              1           0           12      1             No                DSL              No                   Yes                  No                   No                   No                   Month-to-month  1                 Electronic check           51.25           612.1         0      0                                0                  1
6625-IUTTT  0          0              1           0           67      1             No                DSL              Yes                  No                   Yes                  No                   Yes                  Two year        0                 Bank transfer (automatic)  65.55           4361.55       0      0                                0                  1
6625-FLENO  0          0              1           0           58      1             No                No               No internet service  No internet service  No internet service  No internet service  No internet service  Two year        0                 Mailed check               20.75           1185.95       0      1                                0                  1
                                                                                                                                                                                                                                                                                                                                                                                     ..
3352-RICWQ  1          0              1           1           9       1             No                No               No internet service  No internet service  No internet service  No internet service  No internet service  Two year        0                 Mailed check               19.75           210.65        0      1                                0                  1
3352-ALMCK  0          0              1           0           40      1             Yes               Fiber optic      No                   Yes                  Yes                  Yes                  Yes                  Month-to-month  1                 Mailed check               102.65          4108.15       0      0                                0                  1
3351-NQLDI  1          0              1           1           67      1             Yes               Fiber optic      Yes                  No                   No                   No                   Yes                  One year        1                 Credit card (automatic)    94.35           6341.45       1      0                                1                  1
3351-NGXYI  1          1              1           0           16      1             Yes               DSL              Yes                  No                   No                   No                   No                   Month-to-month  1                 Electronic check           54.10           889           0      0                                0                  1
9995-HOTOH  0          0              1           1           63      0             No phone service  DSL              Yes                  Yes                  Yes                  Yes                  Yes                  Two year        0                 Electronic check           59.00           3707.6        0      0                                0                  1
Name: count, Length: 7043, dtype: int64

In [208]:
df_m['StreamingTV'].value_counts()

StreamingTV
No                     2810
Yes                    2707
No internet service    1526
Name: count, dtype: int64

In [209]:
df_m = pd.get_dummies(df_m, columns=['StreamingTV'], prefix='StreamingTV')

In [210]:
bool_cols = ['StreamingTV_Yes', 'StreamingTV_No internet service']  # adjust to your columns
df_m[bool_cols] = df_m[bool_cols].astype(int)

In [211]:
df_m.drop('StreamingTV_No', axis=1, inplace=True)

In [212]:
df_m

,customerID,is_female,SeniorCitizen,Partner_No,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,TechSupport_No internet service,TechSupport_Yes,StreamingTV_No internet service,StreamingTV_Yes
0,7590-VHVEG,1,0,1,0,1,0,No phone service,DSL,No,...,Month-to-month,1,Electronic check,29.85,29.85,0,0,0,0,0
1,5575-GNVDE,0,0,1,0,34,1,No,DSL,Yes,...,One year,0,Mailed check,56.95,1889.5,0,0,0,0,0
2,3668-QPYBK,0,0,1,0,2,1,No,DSL,Yes,...,Month-to-month,1,Mailed check,53.85,108.15,1,0,0,0,0
3,7795-CFOCW,0,0,1,0,45,0,No phone service,DSL,Yes,...,One year,0,Bank transfer (automatic),42.30,1840.75,0,0,1,0,0
4,9237-HQITU,1,0,1,0,2,1,No,Fiber optic,No,...,Month-to-month,1,Electronic check,70.70,151.65,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,0,0,1,1,24,1,Yes,DSL,Yes,...,One year,1,Mailed check,84.80,1990.5,0,0,1,0,1
7039,2234-XADUH,1,0,1,1,72,1,Yes,Fiber optic,No,...,One year,1,Credit card (automatic),103.20,7362.9,0,0,0,0,1
7040,4801-JZAZL,1,0,1,1,11,0,No phone service,DSL,Yes,...,Month-to-month,1,Electronic check,29.60,346.45,0,0,0,0,0
7041,8361-LTMKD,0,1,1,0,4,1,Yes,Fiber optic,No,...,Month-to-month,1,Mailed check,74.40,306.6,1,0,0,0,0
7042,3186-AJIEK,0,0,1,0,66,1,No,Fiber optic,Yes,...,Two year,1,Bank transfer (automatic),105.65,6844.5,0,0,1,0,1

In [213]:
df_m['StreamingMovies'].value_counts()

StreamingMovies
No                     2785
Yes                    2732
No internet service    1526
Name: count, dtype: int64

In [214]:
df_m = pd.get_dummies(df_m, columns=['StreamingMovies'], prefix='StreamingMovies')

In [215]:
bool_cols = ['StreamingMovies_Yes', 'StreamingMovies_No internet service']  # adjust to your columns
df_m[bool_cols] = df_m[bool_cols].astype(int)

In [216]:
df_m.drop('StreamingMovies_No', axis=1, inplace=True)

In [217]:
df_m.head()

,customerID,is_female,SeniorCitizen,Partner_No,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,PaymentMethod,MonthlyCharges,TotalCharges,Churn,TechSupport_No internet service,TechSupport_Yes,StreamingTV_No internet service,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes
0,7590-VHVEG,1,0,1,0,1,0,No phone service,DSL,No,...,Electronic check,29.85,29.85,0,0,0,0,0,0,0
1,5575-GNVDE,0,0,1,0,34,1,No,DSL,Yes,...,Mailed check,56.95,1889.5,0,0,0,0,0,0,0
2,3668-QPYBK,0,0,1,0,2,1,No,DSL,Yes,...,Mailed check,53.85,108.15,1,0,0,0,0,0,0
3,7795-CFOCW,0,0,1,0,45,0,No phone service,DSL,Yes,...,Bank transfer (automatic),42.30,1840.75,0,0,1,0,0,0,0
4,9237-HQITU,1,0,1,0,2,1,No,Fiber optic,No,...,Electronic check,70.70,151.65,1,0,0,0,0,0,0

In [218]:
non_numeric_cols = df_m.select_dtypes(exclude='number').columns

for col in non_numeric_cols:
    print(f"--- {col} ---")
    print(df[col].value_counts())
    print()

--- customerID ---
customerID
7590-VHVEG    1
3791-LGQCY    1
6008-NAIXK    1
5956-YHHRX    1
5365-LLFYV    1
             ..
9796-MVYXX    1
2637-FKFSY    1
1552-AAGRX    1
4304-TSPVK    1
3186-AJIEK    1
Name: count, Length: 7043, dtype: int64

--- MultipleLines ---
MultipleLines
No                  3390
Yes                 2971
No phone service     682
Name: count, dtype: int64

--- InternetService ---
InternetService
Fiber optic    3096
DSL            2421
No             1526
Name: count, dtype: int64

--- OnlineSecurity ---
OnlineSecurity
No                     3498
Yes                    2019
No internet service    1526
Name: count, dtype: int64

--- OnlineBackup ---
OnlineBackup
No                     3088
Yes                    2429
No internet service    1526
Name: count, dtype: int64

--- DeviceProtection ---
DeviceProtection
No                     3095
Yes                    2422
No internet service    1526
Name: count, dtype: int64

--- Contract ---
Contract
Month-to-month    3875
Two year          1695
One year          1473
Name: count, dtype: int64

--- PaymentMethod ---
PaymentMethod
Electronic check             2365
Mailed check                 1612
Bank transfer (automatic)    1544
Credit card (automatic)      1522
Name: count, dtype: int64

--- TotalCharges ---
TotalCharges
          11
20.2      11
19.75      9
20.05      8
19.9       8
          ..
6849.4     1
692.35     1
130.15     1
3211.9     1
6844.5     1
Name: count, Length: 6531, dtype: int64

In [219]:
for col in df_m.columns:
    print(f"--- {col} ({df_m[col].dtype}) ---")
    print(df_m[col].value_counts())
    print()

--- customerID (object) ---
customerID
7590-VHVEG    1
3791-LGQCY    1
6008-NAIXK    1
5956-YHHRX    1
5365-LLFYV    1
             ..
9796-MVYXX    1
2637-FKFSY    1
1552-AAGRX    1
4304-TSPVK    1
3186-AJIEK    1
Name: count, Length: 7043, dtype: int64

--- is_female (int64) ---
is_female
0    3555
1    3488
Name: count, dtype: int64

--- SeniorCitizen (int64) ---
SeniorCitizen
0    5901
1    1142
Name: count, dtype: int64

--- Partner_No (int64) ---
Partner_No
1    7043
Name: count, dtype: int64

--- Dependents (int64) ---
Dependents
0    4933
1    2110
Name: count, dtype: int64

--- tenure (int64) ---
tenure
1     613
72    362
2     238
3     200
4     176
     ...
28     57
39     56
44     51
36     50
0      11
Name: count, Length: 73, dtype: int64

--- PhoneService (int64) ---
PhoneService
1    6361
0     682
Name: count, dtype: int64

--- MultipleLines (object) ---
MultipleLines
No                  3390
Yes                 2971
No phone service     682
Name: count, dtype: int64

--- InternetService (object) ---
InternetService
Fiber optic    3096
DSL            2421
No             1526
Name: count, dtype: int64

--- OnlineSecurity (object) ---
OnlineSecurity
No                     3498
Yes                    2019
No internet service    1526
Name: count, dtype: int64

--- OnlineBackup (object) ---
OnlineBackup
No                     3088
Yes                    2429
No internet service    1526
Name: count, dtype: int64

--- DeviceProtection (object) ---
DeviceProtection
No                     3095
Yes                    2422
No internet service    1526
Name: count, dtype: int64

--- Contract (object) ---
Contract
Month-to-month    3875
Two year          1695
One year          1473
Name: count, dtype: int64

--- PaperlessBilling (int64) ---
PaperlessBilling
1    4171
0    2872
Name: count, dtype: int64

--- PaymentMethod (object) ---
PaymentMethod
Electronic check             2365
Mailed check                 1612
Bank transfer (automatic)    1544
Credit card (automatic)      1522
Name: count, dtype: int64

--- MonthlyCharges (float64) ---
MonthlyCharges
20.05     61
19.85     45
19.95     44
19.90     44
20.00     43
          ..
23.65      1
114.70     1
43.65      1
87.80      1
78.70      1
Name: count, Length: 1585, dtype: int64

--- TotalCharges (object) ---
TotalCharges
          11
20.2      11
19.75      9
20.05      8
19.9       8
          ..
6849.4     1
692.35     1
130.15     1
3211.9     1
6844.5     1
Name: count, Length: 6531, dtype: int64

--- Churn (int64) ---
Churn
0    5174
1    1869
Name: count, dtype: int64

--- TechSupport_No internet service (int64) ---
TechSupport_No internet service
0    5517
1    1526
Name: count, dtype: int64

--- TechSupport_Yes (int64) ---
TechSupport_Yes
0    4999
1    2044
Name: count, dtype: int64

--- StreamingTV_No internet service (int64) ---
StreamingTV_No internet service
0    5517
1    1526
Name: count, dtype: int64

--- StreamingTV_Yes (int64) ---
StreamingTV_Yes
0    4336
1    2707
Name: count, dtype: int64

--- StreamingMovies_No internet service (int64) ---
StreamingMovies_No internet service
0    5517
1    1526
Name: count, dtype: int64

--- StreamingMovies_Yes (int64) ---
StreamingMovies_Yes
0    4311
1    2732
Name: count, dtype: int64

In [220]:
df['Partner'].value_counts()

Partner
No     3641
Yes    3402
Name: count, dtype: int64

In [221]:
df['Partner_Yes'] = df['Partner'].map({'Yes': 1, 'No': 0})

In [222]:
df_m['Partner_No']=df['Partner_Yes']

In [223]:
for col in df_m.columns:
    print(f"--- {col} ({df_m[col].dtype}) ---")
    print(df_m[col].value_counts())
    print()

--- customerID (object) ---
customerID
7590-VHVEG    1
3791-LGQCY    1
6008-NAIXK    1
5956-YHHRX    1
5365-LLFYV    1
             ..
9796-MVYXX    1
2637-FKFSY    1
1552-AAGRX    1
4304-TSPVK    1
3186-AJIEK    1
Name: count, Length: 7043, dtype: int64

--- is_female (int64) ---
is_female
0    3555
1    3488
Name: count, dtype: int64

--- SeniorCitizen (int64) ---
SeniorCitizen
0    5901
1    1142
Name: count, dtype: int64

--- Partner_No (int64) ---
Partner_No
0    3641
1    3402
Name: count, dtype: int64

--- Dependents (int64) ---
Dependents
0    4933
1    2110
Name: count, dtype: int64

--- tenure (int64) ---
tenure
1     613
72    362
2     238
3     200
4     176
     ...
28     57
39     56
44     51
36     50
0      11
Name: count, Length: 73, dtype: int64

--- PhoneService (int64) ---
PhoneService
1    6361
0     682
Name: count, dtype: int64

--- MultipleLines (object) ---
MultipleLines
No                  3390
Yes                 2971
No phone service     682
Name: count, dtype: int64

--- InternetService (object) ---
InternetService
Fiber optic    3096
DSL            2421
No             1526
Name: count, dtype: int64

--- OnlineSecurity (object) ---
OnlineSecurity
No                     3498
Yes                    2019
No internet service    1526
Name: count, dtype: int64

--- OnlineBackup (object) ---
OnlineBackup
No                     3088
Yes                    2429
No internet service    1526
Name: count, dtype: int64

--- DeviceProtection (object) ---
DeviceProtection
No                     3095
Yes                    2422
No internet service    1526
Name: count, dtype: int64

--- Contract (object) ---
Contract
Month-to-month    3875
Two year          1695
One year          1473
Name: count, dtype: int64

--- PaperlessBilling (int64) ---
PaperlessBilling
1    4171
0    2872
Name: count, dtype: int64

--- PaymentMethod (object) ---
PaymentMethod
Electronic check             2365
Mailed check                 1612
Bank transfer (automatic)    1544
Credit card (automatic)      1522
Name: count, dtype: int64

--- MonthlyCharges (float64) ---
MonthlyCharges
20.05     61
19.85     45
19.95     44
19.90     44
20.00     43
          ..
23.65      1
114.70     1
43.65      1
87.80      1
78.70      1
Name: count, Length: 1585, dtype: int64

--- TotalCharges (object) ---
TotalCharges
          11
20.2      11
19.75      9
20.05      8
19.9       8
          ..
6849.4     1
692.35     1
130.15     1
3211.9     1
6844.5     1
Name: count, Length: 6531, dtype: int64

--- Churn (int64) ---
Churn
0    5174
1    1869
Name: count, dtype: int64

--- TechSupport_No internet service (int64) ---
TechSupport_No internet service
0    5517
1    1526
Name: count, dtype: int64

--- TechSupport_Yes (int64) ---
TechSupport_Yes
0    4999
1    2044
Name: count, dtype: int64

--- StreamingTV_No internet service (int64) ---
StreamingTV_No internet service
0    5517
1    1526
Name: count, dtype: int64

--- StreamingTV_Yes (int64) ---
StreamingTV_Yes
0    4336
1    2707
Name: count, dtype: int64

--- StreamingMovies_No internet service (int64) ---
StreamingMovies_No internet service
0    5517
1    1526
Name: count, dtype: int64

--- StreamingMovies_Yes (int64) ---
StreamingMovies_Yes
0    4311
1    2732
Name: count, dtype: int64

In [224]:
cols_to_encode = ['InternetService', 'Contract', 'DeviceProtection', 'OnlineSecurity']

for col in cols_to_encode:
    dummies = pd.get_dummies(df_m[col], prefix=col, drop_first=True)
    dummies = dummies.astype(int)
    df_m = pd.concat([df_m, dummies], axis=1)
    df_m = df_m.drop(col, axis=1)

In [225]:
for col in df_m.columns:
    print(f"--- {col} ({df_m[col].dtype}) ---")
    print(df_m[col].value_counts())
    print()

--- customerID (object) ---
customerID
7590-VHVEG    1
3791-LGQCY    1
6008-NAIXK    1
5956-YHHRX    1
5365-LLFYV    1
             ..
9796-MVYXX    1
2637-FKFSY    1
1552-AAGRX    1
4304-TSPVK    1
3186-AJIEK    1
Name: count, Length: 7043, dtype: int64

--- is_female (int64) ---
is_female
0    3555
1    3488
Name: count, dtype: int64

--- SeniorCitizen (int64) ---
SeniorCitizen
0    5901
1    1142
Name: count, dtype: int64

--- Partner_No (int64) ---
Partner_No
0    3641
1    3402
Name: count, dtype: int64

--- Dependents (int64) ---
Dependents
0    4933
1    2110
Name: count, dtype: int64

--- tenure (int64) ---
tenure
1     613
72    362
2     238
3     200
4     176
     ...
28     57
39     56
44     51
36     50
0      11
Name: count, Length: 73, dtype: int64

--- PhoneService (int64) ---
PhoneService
1    6361
0     682
Name: count, dtype: int64

--- MultipleLines (object) ---
MultipleLines
No                  3390
Yes                 2971
No phone service     682
Name: count, dtype: int64

--- OnlineBackup (object) ---
OnlineBackup
No                     3088
Yes                    2429
No internet service    1526
Name: count, dtype: int64

--- PaperlessBilling (int64) ---
PaperlessBilling
1    4171
0    2872
Name: count, dtype: int64

--- PaymentMethod (object) ---
PaymentMethod
Electronic check             2365
Mailed check                 1612
Bank transfer (automatic)    1544
Credit card (automatic)      1522
Name: count, dtype: int64

--- MonthlyCharges (float64) ---
MonthlyCharges
20.05     61
19.85     45
19.95     44
19.90     44
20.00     43
          ..
23.65      1
114.70     1
43.65      1
87.80      1
78.70      1
Name: count, Length: 1585, dtype: int64

--- TotalCharges (object) ---
TotalCharges
          11
20.2      11
19.75      9
20.05      8
19.9       8
          ..
6849.4     1
692.35     1
130.15     1
3211.9     1
6844.5     1
Name: count, Length: 6531, dtype: int64

--- Churn (int64) ---
Churn
0    5174
1    1869
Name: count, dtype: int64

--- TechSupport_No internet service (int64) ---
TechSupport_No internet service
0    5517
1    1526
Name: count, dtype: int64

--- TechSupport_Yes (int64) ---
TechSupport_Yes
0    4999
1    2044
Name: count, dtype: int64

--- StreamingTV_No internet service (int64) ---
StreamingTV_No internet service
0    5517
1    1526
Name: count, dtype: int64

--- StreamingTV_Yes (int64) ---
StreamingTV_Yes
0    4336
1    2707
Name: count, dtype: int64

--- StreamingMovies_No internet service (int64) ---
StreamingMovies_No internet service
0    5517
1    1526
Name: count, dtype: int64

--- StreamingMovies_Yes (int64) ---
StreamingMovies_Yes
0    4311
1    2732
Name: count, dtype: int64

--- InternetService_Fiber optic (int64) ---
InternetService_Fiber optic
0    3947
1    3096
Name: count, dtype: int64

--- InternetService_No (int64) ---
InternetService_No
0    5517
1    1526
Name: count, dtype: int64

--- Contract_One year (int64) ---
Contract_One year
0    5570
1    1473
Name: count, dtype: int64

--- Contract_Two year (int64) ---
Contract_Two year
0    5348
1    1695
Name: count, dtype: int64

--- DeviceProtection_No internet service (int64) ---
DeviceProtection_No internet service
0    5517
1    1526
Name: count, dtype: int64

--- DeviceProtection_Yes (int64) ---
DeviceProtection_Yes
0    4621
1    2422
Name: count, dtype: int64

--- OnlineSecurity_No internet service (int64) ---
OnlineSecurity_No internet service
0    5517
1    1526
Name: count, dtype: int64

--- OnlineSecurity_Yes (int64) ---
OnlineSecurity_Yes
0    5024
1    2019
Name: count, dtype: int64

In [226]:
cols_to_encode = ['MultipleLines','OnlineBackup']

for col in cols_to_encode:
    dummies = pd.get_dummies(df_m[col], prefix=col, drop_first=True)
    dummies = dummies.astype(int)
    df_m = pd.concat([df_m, dummies], axis=1)
    df_m = df_m.drop(col, axis=1)

In [227]:
for col in df_m.columns:
    print(f"--- {col} ({df_m[col].dtype}) ---")
    print(df_m[col].value_counts())
    print()

--- customerID (object) ---
customerID
7590-VHVEG    1
3791-LGQCY    1
6008-NAIXK    1
5956-YHHRX    1
5365-LLFYV    1
             ..
9796-MVYXX    1
2637-FKFSY    1
1552-AAGRX    1
4304-TSPVK    1
3186-AJIEK    1
Name: count, Length: 7043, dtype: int64

--- is_female (int64) ---
is_female
0    3555
1    3488
Name: count, dtype: int64

--- SeniorCitizen (int64) ---
SeniorCitizen
0    5901
1    1142
Name: count, dtype: int64

--- Partner_No (int64) ---
Partner_No
0    3641
1    3402
Name: count, dtype: int64

--- Dependents (int64) ---
Dependents
0    4933
1    2110
Name: count, dtype: int64

--- tenure (int64) ---
tenure
1     613
72    362
2     238
3     200
4     176
     ...
28     57
39     56
44     51
36     50
0      11
Name: count, Length: 73, dtype: int64

--- PhoneService (int64) ---
PhoneService
1    6361
0     682
Name: count, dtype: int64

--- PaperlessBilling (int64) ---
PaperlessBilling
1    4171
0    2872
Name: count, dtype: int64

--- PaymentMethod (object) ---
PaymentMethod
Electronic check             2365
Mailed check                 1612
Bank transfer (automatic)    1544
Credit card (automatic)      1522
Name: count, dtype: int64

--- MonthlyCharges (float64) ---
MonthlyCharges
20.05     61
19.85     45
19.95     44
19.90     44
20.00     43
          ..
23.65      1
114.70     1
43.65      1
87.80      1
78.70      1
Name: count, Length: 1585, dtype: int64

--- TotalCharges (object) ---
TotalCharges
          11
20.2      11
19.75      9
20.05      8
19.9       8
          ..
6849.4     1
692.35     1
130.15     1
3211.9     1
6844.5     1
Name: count, Length: 6531, dtype: int64

--- Churn (int64) ---
Churn
0    5174
1    1869
Name: count, dtype: int64

--- TechSupport_No internet service (int64) ---
TechSupport_No internet service
0    5517
1    1526
Name: count, dtype: int64

--- TechSupport_Yes (int64) ---
TechSupport_Yes
0    4999
1    2044
Name: count, dtype: int64

--- StreamingTV_No internet service (int64) ---
StreamingTV_No internet service
0    5517
1    1526
Name: count, dtype: int64

--- StreamingTV_Yes (int64) ---
StreamingTV_Yes
0    4336
1    2707
Name: count, dtype: int64

--- StreamingMovies_No internet service (int64) ---
StreamingMovies_No internet service
0    5517
1    1526
Name: count, dtype: int64

--- StreamingMovies_Yes (int64) ---
StreamingMovies_Yes
0    4311
1    2732
Name: count, dtype: int64

--- InternetService_Fiber optic (int64) ---
InternetService_Fiber optic
0    3947
1    3096
Name: count, dtype: int64

--- InternetService_No (int64) ---
InternetService_No
0    5517
1    1526
Name: count, dtype: int64

--- Contract_One year (int64) ---
Contract_One year
0    5570
1    1473
Name: count, dtype: int64

--- Contract_Two year (int64) ---
Contract_Two year
0    5348
1    1695
Name: count, dtype: int64

--- DeviceProtection_No internet service (int64) ---
DeviceProtection_No internet service
0    5517
1    1526
Name: count, dtype: int64

--- DeviceProtection_Yes (int64) ---
DeviceProtection_Yes
0    4621
1    2422
Name: count, dtype: int64

--- OnlineSecurity_No internet service (int64) ---
OnlineSecurity_No internet service
0    5517
1    1526
Name: count, dtype: int64

--- OnlineSecurity_Yes (int64) ---
OnlineSecurity_Yes
0    5024
1    2019
Name: count, dtype: int64

--- MultipleLines_No phone service (int64) ---
MultipleLines_No phone service
0    6361
1     682
Name: count, dtype: int64

--- MultipleLines_Yes (int64) ---
MultipleLines_Yes
0    4072
1    2971
Name: count, dtype: int64

--- OnlineBackup_No internet service (int64) ---
OnlineBackup_No internet service
0    5517
1    1526
Name: count, dtype: int64

--- OnlineBackup_Yes (int64) ---
OnlineBackup_Yes
0    4614
1    2429
Name: count, dtype: int64

In [228]:
dummies = pd.get_dummies(df_m['PaymentMethod'], prefix='PaymentMethod', drop_first=True)
dummies = dummies.astype(int)
df_m = pd.concat([df_m, dummies], axis=1).drop('PaymentMethod', axis=1)

In [234]:
from sklearn.preprocessing import StandardScaler

cols_to_scale = ['tenure', 'MonthlyCharges', 'TotalCharges']

for col in cols_to_scale:
    df_m[col] = pd.to_numeric(df_m[col], errors='coerce')
    df_m[col] = df_m[col].fillna(df_m[col].median())

scaler = StandardScaler()
for col in cols_to_scale:
    df_m[col] = scaler.fit_transform(df_m[[col]])

In [235]:
dummies = pd.get_dummies(df_m['Contract'], prefix='Contract', drop_first=True)
dummies = dummies.astype(int)
df_m = pd.concat([df_m, dummies], axis=1).drop('Contract', axis=1)

KeyError: 'Contract'